baseURL = "https://instrumenta.dev/"
languageCode = "en-gb"
title = "Instrumenta"
theme = "kube"
pygmentsCodefences = true
pygmentsStyle = "solarized-dark"

googleAnalytics = "UA-435455-17"


[params]
primaryColor = "#3B248D"
secondaryColor = "#F9FAF5"
gradientTopColor = "#3B248D"
gradientBottomColor = "#6E3BC5"
textColor = "#636363"
textColorDark = "#043698"
whiteColor = "#FFF"

[menu]
  [[menu.main]]
    weight = 1
    name = "About"
    url = "/about"

  [[menu.main]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/instrumenta"
